"use client";

import React from "react";
// 1. ADD THIS IMPORT LINE TO FIX THE ERROR
import { 
  Search, Globe, ShieldCheck, 
  BarChart3, Cpu, Layers, Zap, 
  ArrowRight, CheckCircle2 
} from "lucide-react";

import Navbar from "@/components/layout/Navbar";
import Hero from "@/components/sections/Hero";
import { AuroraCard } from "@/components/ui/AuroraCard"; // Ensure this path matches where you saved the component
import { ProcessCard } from "@/components/ui/ProcessCard";
import { ProcessAccordion } from "@/components/ui/ProcessAccordion";
import { CTA } from "@/components/sections/CTA";
import { CTA_Split } from "@/components/sections/CTA_Split";
import Footer from "@/components/layout/Footer";

// Reusable Section Header
const SectionHeader = ({ badge, title, subtitle }: { badge: string, title: string, subtitle: string }) => (
  <div className="text-center max-w-3xl mx-auto mb-20">
    <span className="inline-block py-1 px-3 rounded-full bg-white/5 border border-white/10 text-purple-400 text-xs font-semibold tracking-wider mb-6">
      {badge}
    </span>
    <h2 className="text-4xl md:text-5xl font-bold mb-6 tracking-tight text-white">
      {title}
    </h2>
    <p className="text-lg text-gray-400 leading-relaxed">
      {subtitle}
    </p>
  </div>
);

export default function Home() {
  return (
    <main className="bg-[#050505] min-h-screen text-white selection:bg-purple-500/30">
      
      <Navbar />
      
      {/* 1. Hero Section */}
      <Hero />

      {/* 2. Problem / Context Section */}
      <section id="about" className="py-32 px-6 relative overflow-hidden">
        {/* Subtle background glow */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[1000px] h-[600px] bg-indigo-900/10 blur-[120px] rounded-full pointer-events-none" />

        <div className="max-w-7xl mx-auto relative z-10">
          <div className="grid md:grid-cols-2 gap-16 items-center">
            <div>
              <h2 className="text-4xl md:text-5xl font-bold mb-8 leading-tight">
                Traditional SEO is <br />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400">
                  no longer enough.
                </span>
              </h2>
              <div className="space-y-8">
                {[
                  {
                    title: "The Search Paradigm Shift",
                    desc: "Users don't just search anymore—they ask. LLMs scrape and summarize content, bypassing traditional blue links."
                  },
                  {
                    title: "The Visibility Gap",
                    desc: "If your brand isn't optimized for AI retrieval, you disappear from the answers generated by ChatGPT and Gemini."
                  }
                ].map((item, idx) => (
                  <div key={idx} className="flex gap-4">
                    <div className="mt-1">
                      <div className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center border border-white/10">
                        <CheckCircle2 size={16} className="text-purple-400" />
                      </div>
                    </div>
                    <div>
                      <h3 className="text-xl font-semibold text-white mb-2">{item.title}</h3>
                      <p className="text-gray-400 leading-relaxed">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            
            {/* Visual: Glass Panel illustrating AI scraping */}
            <div className="relative">
              <div className="absolute inset-0 bg-gradient-to-r from-purple-500 to-pink-500 rounded-3xl blur-2xl opacity-20" />
              <div className="bg-black/40 backdrop-blur-xl border border-white/10 rounded-3xl p-8 relative">
                <div className="flex items-center gap-3 mb-6 border-b border-white/5 pb-4">
                  <div className="w-3 h-3 rounded-full bg-red-500/50" />
                  <div className="w-3 h-3 rounded-full bg-yellow-500/50" />
                  <div className="w-3 h-3 rounded-full bg-green-500/50" />
                  <div className="ml-auto text-xs text-gray-500 font-mono">ai_response.json</div>
                </div>
                <div className="space-y-4 font-mono text-sm">
                  <div className="text-gray-500">{"// AI generating response..."}</div>
                  <div className="text-purple-300">
                    <span className="text-pink-400">const</span> bestBrand = <span className="text-yellow-300">"Kasparro Optimized Client"</span>;
                  </div>
                  <div className="text-gray-400">
                    summary: "Based on verified data sources, this brand offers the most authoritative solution..."
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 3. Services Section (UPDATED WITH AURORA CARD) */}
      <section id="services" className="py-32 px-6 relative">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full max-w-4xl h-[600px] bg-purple-900/10 blur-[120px] rounded-full pointer-events-none" />

        <div className="relative z-10 max-w-7xl mx-auto">
          <SectionHeader 
            badge="OUR EXPERTISE"
            title="Shape Your AI Identity"
            subtitle="We analyze your digital presence and optimize your brand so it appears at the top of AI-generated results."
          />
          
          <div className="grid md:grid-cols-3 gap-6 auto-rows-fr">
            {[
              { 
                icon: <Search size={24} />, 
                title: "LLM Gap Analysis", 
                desc: "We analyze how models currently perceive your brand versus your competitors, identifying critical missing data points." 
              },
              { 
                icon: <Globe size={24} />, 
                title: "Knowledge Graph Opt.", 
                desc: "Feed AI structured data to ensure factual accuracy. We build the schema that tells Google and GPT exactly who you are." 
              },
              { 
                icon: <ShieldCheck size={24} />, 
                title: "Brand Authority", 
                desc: "Protect your brand reputation in AI-generated summaries. We ensure the 'sentiment' of AI answers leans positive." 
              },
            ].map((service, idx) => (
              <div key={idx} className="h-full">
                <AuroraCard 
                  title={service.title} 
                  desc={service.desc} 
                  icon={service.icon} 
                />
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 4. How It Works (Process) */}
      <section id="process" className="py-32 px-6 relative bg-black">
        <div className="max-w-7xl mx-auto">
          <SectionHeader 
            badge="PROCESS"
            title="How We Do It"
            subtitle="A data-driven approach to dominating the AI Search Era."
          />

          {/* This one line replaces the whole grid map */}
          <ProcessAccordion />
          
        </div>
      </section>

      {/* 5. CTA Section */}
      <CTA_Split />

      {/* 6. Footer */}
      <Footer />

    </main>
  );
}