"use client";

import React from "react";
import { motion } from "framer-motion";
import { 
  Search, Globe, ShieldCheck, 
  BarChart3, ArrowRight, CheckCircle2,
  Cpu, Layers, Zap
} from "lucide-react";

// --- Imports from your new structure ---
import Navbar from "@/components/layout/Navbar";
import Hero from "@/components/sections/Hero";

// --- Reusable "Aurora" Style Components ---

const SectionHeader = ({ badge, title, subtitle }: { badge: string, title: string, subtitle: string }) => (
  <div className="text-center max-w-3xl mx-auto mb-20">
    <span className="inline-block py-1 px-3 rounded-full bg-white/5 border border-white/10 text-purple-400 text-xs font-semibold tracking-wider mb-6">
      {badge}
    </span>
    <h2 className="text-4xl md:text-5xl font-bold mb-6 tracking-tight text-white">
      {title}
    </h2>
    <p className="text-lg text-gray-400 leading-relaxed">
      {subtitle}
    </p>
  </div>
);

const GlassCard = ({ children, className = "" }: { children: React.ReactNode, className?: string }) => (
  <motion.div 
    whileHover={{ y: -5 }}
    className={`bg-white/5 backdrop-blur-lg border border-white/10 p-8 rounded-3xl hover:bg-white/10 hover:border-white/20 transition-all duration-300 ${className}`}
  >
    {children}
  </motion.div>
);

// --- MAIN PAGE COMPONENT ---

export default function Home() {
  return (
    <main className="bg-[#050505] min-h-screen text-white selection:bg-purple-500/30">
      
      <Navbar />
      
      {/* 1. Hero Section (Imported) */}
      <Hero />

      {/* 2. Problem / Context Section */}
      <section id="about" className="py-32 px-6 relative overflow-hidden">
        {/* Subtle background glow for this section */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[1000px] h-[600px] bg-indigo-900/20 blur-[120px] rounded-full pointer-events-none" />

        <div className="max-w-7xl mx-auto relative z-10">
          <div className="grid md:grid-cols-2 gap-16 items-center">
            <div>
              <h2 className="text-4xl md:text-5xl font-bold mb-8 leading-tight">
                Traditional SEO is <br />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400">
                  no longer enough.
                </span>
              </h2>
              <div className="space-y-8">
                {[
                  {
                    title: "The Search Paradigm Shift",
                    desc: "Users don't just search anymore—they ask. Large Language Models (LLMs) scrape and summarize content, bypassing traditional blue links."
                  },
                  {
                    title: "The Visibility Gap",
                    desc: "If your brand isn't optimized for AI retrieval, you disappear from the answers generated by ChatGPT, Gemini, and Claude."
                  }
                ].map((item, idx) => (
                  <div key={idx} className="flex gap-4">
                    <div className="mt-1">
                      <div className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center border border-white/10">
                        <CheckCircle2 size={16} className="text-purple-400" />
                      </div>
                    </div>
                    <div>
                      <h3 className="text-xl font-semibold text-white mb-2">{item.title}</h3>
                      <p className="text-gray-400 leading-relaxed">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            
            {/* Visual: Glass Panel illustrating AI scraping */}
            <div className="relative">
              <div className="absolute inset-0 bg-gradient-to-r from-purple-500 to-pink-500 rounded-3xl blur-2xl opacity-20" />
              <div className="bg-black/40 backdrop-blur-xl border border-white/10 rounded-3xl p-8 relative">
                <div className="flex items-center gap-3 mb-6 border-b border-white/5 pb-4">
                  <div className="w-3 h-3 rounded-full bg-red-500/50" />
                  <div className="w-3 h-3 rounded-full bg-yellow-500/50" />
                  <div className="w-3 h-3 rounded-full bg-green-500/50" />
                  <div className="ml-auto text-xs text-gray-500 font-mono">ai_response.json</div>
                </div>
                <div className="space-y-4 font-mono text-sm">
                  <div className="text-gray-500">{"// AI generating response..."}</div>
                  <div className="text-purple-300">
                    <span className="text-pink-400">const</span> bestBrand = <span className="text-yellow-300">"Kasparro Optimized Client"</span>;
                  </div>
                  <div className="text-gray-400">
                    summary: "Based on verified data sources, this brand offers the most authoritative solution..."
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 3. Services Section */}
      <section id="services" className="py-32 px-6 bg-white/[0.02]">
        <SectionHeader 
          badge="OUR EXPERTISE"
          title="Shape Your AI Identity"
          subtitle="We analyze your digital presence and optimize your brand so it appears at the top of AI-generated results."
        />
        
        <div className="max-w-7xl mx-auto grid md:grid-cols-3 gap-6">
          {[
            { 
              icon: <Search className="text-purple-400" />, 
              title: "LLM Gap Analysis", 
              desc: "We analyze how models currently perceive your brand versus your competitors." 
            },
            { 
              icon: <Globe className="text-pink-400" />, 
              title: "Knowledge Graph Opt.", 
              desc: "Feed AI structured data to ensure factual accuracy and citation." 
            },
            { 
              icon: <ShieldCheck className="text-orange-400" />, 
              title: "Brand Authority", 
              desc: "Protect your brand reputation in AI-generated summaries and answers." 
            },
          ].map((service, idx) => (
            <GlassCard key={idx} className="hover:shadow-[0_0_30px_-5px_rgba(168,85,247,0.15)]">
              <div className="w-12 h-12 rounded-2xl bg-white/5 flex items-center justify-center mb-6 text-white border border-white/10">
                {service.icon}
              </div>
              <h3 className="text-xl font-bold mb-3">{service.title}</h3>
              <p className="text-gray-400 leading-relaxed">{service.desc}</p>
            </GlassCard>
          ))}
        </div>
      </section>

      {/* 4. How It Works (Process) */}
      <section id="process" className="py-32 px-6 relative">
        <div className="max-w-7xl mx-auto">
          <SectionHeader 
            badge="PROCESS"
            title="How We Do It"
            subtitle="A data-driven approach to dominating the AI Search Era."
          />

          <div className="grid md:grid-cols-4 gap-8 relative">
            {/* Connecting Gradient Line */}
            <div className="hidden md:block absolute top-12 left-0 w-full h-[2px] bg-gradient-to-r from-purple-500/0 via-purple-500/50 to-purple-500/0" />

            {[
              { step: "01", title: "Analyze", icon: BarChart3 },
              { step: "02", title: "Optimize", icon: Cpu },
              { step: "03", title: "Monitor", icon: Layers },
              { step: "04", title: "Dominate", icon: Zap },
            ].map((item, idx) => (
              <div key={idx} className="relative pt-8 text-center group">
                <div className="w-16 h-16 mx-auto bg-[#0a0a0a] border border-white/10 rounded-2xl flex items-center justify-center relative z-10 mb-6 group-hover:border-purple-500/50 transition-colors shadow-lg">
                  <item.icon className="text-gray-400 group-hover:text-purple-400 transition-colors" />
                </div>
                <h3 className="text-lg font-bold mb-2">{item.title}</h3>
                <p className="text-sm text-gray-500">Step {item.step}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 5. CTA Section */}
      <section className="py-20 px-6">
        <div className="max-w-5xl mx-auto">
          <div className="relative rounded-[3rem] overflow-hidden p-12 md:p-24 text-center border border-white/10">
            {/* Background Gradient Mesh inside Card */}
            <div className="absolute inset-0 bg-[#0a0a0a]" />
            <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-purple-900/20 via-transparent to-orange-900/20 opacity-50" />
            
            <div className="relative z-10">
              <h2 className="text-4xl md:text-6xl font-bold mb-8 text-white tracking-tight">
                Be the Brand <br /> AI Recommends.
              </h2>
              <div className="flex flex-col sm:flex-row justify-center gap-4">
                <button className="px-8 py-4 rounded-full bg-white text-black font-bold hover:bg-gray-200 transition-all flex items-center justify-center gap-2">
                  Get Started Now <ArrowRight size={18} />
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 6. Footer */}
      <footer className="border-t border-white/5 py-12 bg-black">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center text-white font-bold text-xs">
              K
            </div>
            <span className="font-bold text-gray-200">Kasparro</span>
          </div>
          <p className="text-gray-600 text-sm">
            © {new Date().getFullYear()} Kasparro Inc. All rights reserved.
          </p>
          <div className="flex gap-6">
            {['Twitter', 'LinkedIn', 'Email'].map(link => (
              <a key={link} href="#" className="text-gray-500 hover:text-white text-sm transition-colors">
                {link}
              </a>
            ))}
          </div>
        </div>
      </footer>

    </main>
  );
}